language: php
php:
    - 7.0
    - 7.1
    - 7.2

env:
    - UNIT_TESTS=yes
    - PHP_LINT=yes
    - PHP_CS_FIXER=yes

sudo: false

addons:
    apt:
        packages:
            - parallel

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - mkdir -p logs
    - rm -rf .build/
    - composer install --no-interaction --no-progress

script:
    - >
        if [[ "$PHP_LINT" == "yes" ]]; then
            echo;
            echo "PHP lint";
            find . -name \*.php ! -path "./.build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
        fi
    - >
        if [[ "$PHP_CS_FIXER" == "yes" ]]; then
            echo;
            echo "PHP CS Fixer";
            ./.build/bin/php-cs-fixer fix --config Build/.php_cs.dist --format=junit > logs/php-cs-fixer.xml
        fi

    - >
        if [[ "$UNIT_TESTS" == "yes" ]]; then
            echo;
            echo "Unit tests";
            .build/vendor/phpunit/phpunit/phpunit -c Build/UnitTests.xml --log-junit logs/phpunit.xml  --coverage-clover logs/coverage.xml --coverage-html logs/coverage/
        fi
