name: CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        typo3: [ ^9.5, ^10.4 ]
        php: [ '7.2', '7.3', '7.4' ]

    steps:
      - name: Start database server
        run: sudo /etc/init.d/mysql start

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, php-cs-fixer

      - name: Environment Check
        run: |
          php --version
          composer --version

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json

      - name: Info
        run: composer info

      - name: CGL
        run: php-cs-fixer fix --dry-run --verbose

      - name: Lint PHP
        run: composer t3g:test:php:lint

      - name: Unit Tests without coverage
        if: matrix.typo3 == '^9.5'
        run: composer t3g:test:php:unit

      - name: Unit Tests with coverage
        if: matrix.typo3 == '^10.4'
        run: composer t3g:test:php:unit:cover

      - name: Functional Tests without coverage
        run: composer t3g:test:php:functional
        if: matrix.typo3 == '^9.5'
        env:
          typo3DatabaseHost: 127.0.0.1
          typo3DatabaseName: t3func
          typo3DatabasePassword: root
          typo3DatabaseUsername: root

      - name: Functional Tests with coverage
        run: composer t3g:test:php:functional:cover
        if: matrix.typo3 == '^10.4'
        env:
          typo3DatabaseHost: 127.0.0.1
          typo3DatabaseName: t3func
          typo3DatabasePassword: root
          typo3DatabaseUsername: root

      - name: Upload coverage results to Coveralls
        if: matrix.typo3 == '^10.4'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: php-${{ matrix.php }}
        run: |
          composer global require twinh/php-coveralls --no-progress --no-suggest --no-interaction
          /home/runner/.composer/vendor/bin/php-coveralls --coverage_clover=var/log/junit/coverage-unit.xml --coverage_clover=var/log/junit/coverage-functional.xml -vvv --json_path=var/log/coveralls-upload.json

  coveralls-finish:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
